"""
Sistema de traducción simple con diccionario estático
"""

import logging
import json
import os
from typing import Dict, Any, Optional, List

logger = logging.getLogger(__name__)

# Traducciones estáticas
TRANSLATIONS = {
    'es': {
        'dashboard': 'Panel de Control',
        'reports': 'Informes', 
        'ai_chat': 'Chat IA',
        'about': 'Acerca de',
        'recent_articles': 'Artículos Recientes',
        'high_risk_articles': 'Artículos de Alto Riesgo',
        'language_distribution': 'Distribución por Idioma',
        'ai_geopolitical_analysis': 'Análisis Geopolítico por IA',
        'key_insights': 'Percepciones Clave',
        'recommendations': 'Recomendaciones',
        'title': 'Título',
        'description': 'Descripción',
        'published': 'Publicado',
        'source': 'Fuente',
        'language': 'Idioma',
        'risk_level': 'Nivel de Riesgo',
        'sentiment': 'Sentimiento',
        'loading': 'Cargando...',
        'error': 'Error',
        'high': 'Alto',
        'medium': 'Medio',
        'low': 'Bajo',
        'positive': 'Positivo',
        'negative': 'Negativo',
        'neutral': 'Neutral',
        'articles': 'Artículos',
        'total_articles': 'Total de Artículos',
        'sources': 'Fuentes',
        'risk_index': 'Índice de Riesgo',
        'select_language': 'Seleccionar Idioma',
        'geopolitical_intelligence_system': 'Sistema de Inteligencia Geopolítica',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': 'Construido con tecnologías avanzadas de IA y NLP',
        'copyright': '© 2025 Sistema de Inteligencia Geopolítica'
    },
    'de': {
        'dashboard': 'Dashboard',
        'reports': 'Berichte', 
        'ai_chat': 'KI-Chat',
        'about': 'Über',
        'recent_articles': 'Aktuelle Artikel',
        'high_risk_articles': 'Hochrisiko-Artikel',
        'language_distribution': 'Sprachverteilung',
        'ai_geopolitical_analysis': 'KI-Geopolitische Analyse',
        'key_insights': 'Wichtige Erkenntnisse',
        'recommendations': 'Empfehlungen',
        'title': 'Titel',
        'description': 'Beschreibung',
        'published': 'Veröffentlicht',
        'source': 'Quelle',
        'language': 'Sprache',
        'risk_level': 'Risikostufe',
        'sentiment': 'Stimmung',
        'loading': 'Wird geladen...',
        'error': 'Fehler',
        'high': 'Hoch',
        'medium': 'Mittel',
        'low': 'Niedrig',
        'positive': 'Positiv',
        'negative': 'Negativ',
        'neutral': 'Neutral',
        'articles': 'Artikel',
        'total_articles': 'Artikel insgesamt',
        'sources': 'Quellen',
        'risk_index': 'Risikoindex',
        'select_language': 'Sprache auswählen',
        'geopolitical_intelligence_system': 'Geopolitisches Intelligenzsystem',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': 'Erstellt mit fortschrittlichen KI- und NLP-Technologien',
        'copyright': '© 2025 Geopolitisches Intelligenzsystem'
    },
    'fr': {
        'dashboard': 'Tableau de Bord',
        'reports': 'Rapports', 
        'ai_chat': 'Chat IA',
        'about': 'À propos',
        'recent_articles': 'Articles Récents',
        'high_risk_articles': 'Articles à Haut Risque',
        'language_distribution': 'Distribution par Langue',
        'ai_geopolitical_analysis': 'Analyse Géopolitique par IA',
        'key_insights': 'Aperçus Clés',
        'recommendations': 'Recommandations',
        'title': 'Titre',
        'description': 'Description',
        'published': 'Publié',
        'source': 'Source',
        'language': 'Langue',
        'risk_level': 'Niveau de Risque',
        'sentiment': 'Sentiment',
        'loading': 'Chargement...',
        'error': 'Erreur',
        'high': 'Élevé',
        'medium': 'Moyen',
        'low': 'Faible',
        'positive': 'Positif',
        'negative': 'Négatif',
        'neutral': 'Neutre',
        'articles': 'Articles',
        'total_articles': 'Total des Articles',
        'sources': 'Sources',
        'risk_index': 'Indice de Risque',
        'select_language': 'Sélectionner la Langue',
        'geopolitical_intelligence_system': 'Système d\'Intelligence Géopolitique',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': 'Construit avec des technologies avancées d\'IA et NLP',
        'copyright': '© 2025 Système d\'Intelligence Géopolitique'
    },
    'it': {
        'dashboard': 'Cruscotto',
        'reports': 'Rapporti', 
        'ai_chat': 'Chat IA',
        'about': 'Informazioni',
        'recent_articles': 'Articoli Recenti',
        'high_risk_articles': 'Articoli ad Alto Rischio',
        'language_distribution': 'Distribuzione per Lingua',
        'ai_geopolitical_analysis': 'Analisi Geopolitica IA',
        'key_insights': 'Intuizioni Chiave',
        'recommendations': 'Raccomandazioni',
        'title': 'Titolo',
        'description': 'Descrizione',
        'published': 'Pubblicato',
        'source': 'Fonte',
        'language': 'Lingua',
        'risk_level': 'Livello di Rischio',
        'sentiment': 'Sentimento',
        'loading': 'Caricamento...',
        'error': 'Errore',
        'high': 'Alto',
        'medium': 'Medio',
        'low': 'Basso',
        'positive': 'Positivo',
        'negative': 'Negativo',
        'neutral': 'Neutrale',
        'articles': 'Articoli',
        'total_articles': 'Totale Articoli',
        'sources': 'Fonti',
        'risk_index': 'Indice di Rischio',
        'select_language': 'Seleziona Lingua',
        'geopolitical_intelligence_system': 'Sistema di Intelligence Geopolitica',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': 'Costruito con tecnologie avanzate di IA e NLP',
        'copyright': '© 2025 Sistema di Intelligence Geopolitica'
    },
    'ru': {
        'dashboard': 'Панель управления',
        'reports': 'Отчеты', 
        'ai_chat': 'ИИ Чат',
        'about': 'О нас',
        'recent_articles': 'Последние статьи',
        'high_risk_articles': 'Статьи высокого риска',
        'language_distribution': 'Распределение по языкам',
        'ai_geopolitical_analysis': 'Геополитический анализ ИИ',
        'key_insights': 'Ключевые выводы',
        'recommendations': 'Рекомендации',
        'title': 'Заголовок',
        'description': 'Описание',
        'published': 'Опубликовано',
        'source': 'Источник',
        'language': 'Язык',
        'risk_level': 'Уровень риска',
        'sentiment': 'Настроение',
        'loading': 'Загрузка...',
        'error': 'Ошибка',
        'high': 'Высокий',
        'medium': 'Средний',
        'low': 'Низкий',
        'positive': 'Положительный',
        'negative': 'Отрицательный',
        'neutral': 'Нейтральный',
        'articles': 'Статьи',
        'total_articles': 'Всего статей',
        'sources': 'Источники',
        'risk_index': 'Индекс риска',
        'select_language': 'Выбрать язык',
        'geopolitical_intelligence_system': 'Система геополитической разведки',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': 'Создано с помощью передовых технологий ИИ и NLP',
        'copyright': '© 2025 Система геополитической разведки'
    },
    'zh': {
        'dashboard': '仪表板',
        'reports': '报告', 
        'ai_chat': 'AI聊天',
        'about': '关于',
        'recent_articles': '最新文章',
        'high_risk_articles': '高风险文章',
        'language_distribution': '语言分布',
        'ai_geopolitical_analysis': 'AI地缘政治分析',
        'key_insights': '关键洞察',
        'recommendations': '建议',
        'title': '标题',
        'description': '描述',
        'published': '发布时间',
        'source': '来源',
        'language': '语言',
        'risk_level': '风险等级',
        'sentiment': '情感',
        'loading': '加载中...',
        'error': '错误',
        'high': '高',
        'medium': '中',
        'low': '低',
        'positive': '积极',
        'negative': '消极',
        'neutral': '中性',
        'articles': '文章',
        'total_articles': '文章总数',
        'sources': '来源',
        'risk_index': '风险指数',
        'select_language': '选择语言',
        'geopolitical_intelligence_system': '地缘政治情报系统',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': '采用先进的AI和NLP技术构建',
        'copyright': '© 2025 地缘政治情报系统'
    },
    'ja': {
        'dashboard': 'ダッシュボード',
        'reports': 'レポート', 
        'ai_chat': 'AIチャット',
        'about': 'について',
        'recent_articles': '最新記事',
        'high_risk_articles': '高リスク記事',
        'language_distribution': '言語分布',
        'ai_geopolitical_analysis': 'AI地政学分析',
        'key_insights': '主要洞察',
        'recommendations': '推奨事項',
        'title': 'タイトル',
        'description': '説明',
        'published': '公開日',
        'source': 'ソース',
        'language': '言語',
        'risk_level': 'リスクレベル',
        'sentiment': 'センチメント',
        'loading': '読み込み中...',
        'error': 'エラー',
        'high': '高',
        'medium': '中',
        'low': '低',
        'positive': 'ポジティブ',
        'negative': 'ネガティブ',
        'neutral': 'ニュートラル',
        'articles': '記事',
        'total_articles': '記事総数',
        'sources': 'ソース',
        'risk_index': 'リスクインデックス',
        'select_language': '言語を選択',
        'geopolitical_intelligence_system': '地政学的情報システム',
        'osint_intelligence': 'OSINT Intelligence',
        'built_with_ai': '高度なAIとNLP技術で構築',
        'copyright': '© 2025 地政学的情報システム'
    }
}

class SimpleTranslator:
    """Traductor simple basado en diccionario"""
    
    def __init__(self):
        self.translations = TRANSLATIONS
    
    def get_ui_translations(self, target_lang: str) -> Dict[str, str]:
        """Obtiene traducciones para elementos de la interfaz"""
        if target_lang == 'en' or target_lang not in self.translations:
            # Retornar textos en inglés por defecto
            return {
                'dashboard': 'Dashboard',
                'reports': 'Reports', 
                'ai_chat': 'AI Chat',
                'about': 'About',
                'recent_articles': 'Recent Articles',
                'high_risk_articles': 'High Risk Articles',
                'language_distribution': 'Language Distribution',
                'ai_geopolitical_analysis': 'AI Geopolitical Analysis',
                'key_insights': 'Key Insights',
                'recommendations': 'Recommendations',
                'title': 'Title',
                'description': 'Description',
                'published': 'Published',
                'source': 'Source',
                'language': 'Language',
                'risk_level': 'Risk Level',
                'sentiment': 'Sentiment',
                'loading': 'Loading...',
                'error': 'Error',
                'high': 'High',
                'medium': 'Medium',
                'low': 'Low',
                'positive': 'Positive',
                'negative': 'Negative',
                'neutral': 'Neutral',
                'articles': 'Articles',
                'total_articles': 'Total Articles',
                'sources': 'Sources',
                'risk_index': 'Risk Index',
                'select_language': 'Select Language',
                'geopolitical_intelligence_system': 'Geopolitical Intelligence System',
                'osint_intelligence': 'OSINT Intelligence',
                'built_with_ai': 'Built with advanced AI and NLP technologies',
                'copyright': '© 2025 Geopolitical Intelligence System'
            }
        
        return self.translations[target_lang]
    
    def translate(self, text: str, target_lang: str, source_lang: str = 'en') -> str:
        """Traduce un texto simple (no implementado para textos largos)"""
        # Para artículos largos, simplemente retornamos el texto original
        return text
    
    def translate_articles_list(self, articles: List[Dict[str, Any]], target_lang: str) -> List[Dict[str, Any]]:
        """Para artículos, simplemente retornamos la lista original"""
        return articles

# Instancia global del traductor
simple_translator = SimpleTranslator()

def get_translator() -> SimpleTranslator:
    """Obtiene la instancia del traductor"""
    return simple_translator
