name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black mypy flake8
    - name: Lint with flake8
      run: |
        flake8 src tests
    - name: Run tests with coverage
      run: |
        pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml
    - name: Check formatting with Black
      run: |
        black --check src tests
    - name: Type check with mypy
      run: |
        mypy src
    - name: Upload coverage report
      if: success()
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: true
